appName: adservice
appImage: 667516053986.dkr.ecr.ap-south-1.amazonaws.com/adservice
appVersion: latest
appReplicas: 2
containerPort: 9555
containerEnvVars: 
- name: PORT
  value: "9555"

servicePort: 9555