appName: cartservice
appImage: 667516053986.dkr.ecr.ap-south-1.amazonaws.com/cartservice
appReplicas: 2
containerPort: 7070
containerEnvVars: 
- name: PORT
  value: "7070"
- name: REDIS_ADDR
  value: "redis-cart:6379"

servicePort: 7070