appName: currencyservice
appImage: 667516053986.dkr.ecr.ap-south-1.amazonaws.com/currencyservice
appVersion: latest
appReplicas: 2
containerPort: 7000
containerEnvVars: 
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 7000