appName: emailservice
appImage: 667516053986.dkr.ecr.ap-south-1.amazonaws.com/emailservice
appVersion: latest
appReplicas: 2
containerPort: 8080
containerEnvVars: 
- name: PORT
  value: "8080"

servicePort: 5000