appName: paymentservice
appImage: 667516053986.dkr.ecr.ap-south-1.amazonaws.com/paymentservice
appReplicas: 2
containerPort: 50051
containerEnvVars: 
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 50051