appName: productcatalogservice
appImage: docker.io/c0dysharma/productcatalogservice
appVersion: 2
appReplicas: 2
containerPort: 3550
containerEnvVars: 
- name: PORT
  value: "3550"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 3550