appName: recommendationservice
appImage: docker.io/c0dysharma/recommendationservice
appVersion: 1
appReplicas: 2
containerPort: 8080
containerEnvVars: 
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"

servicePort: 8080