appName: recommendationservice
appImage: 667516053986.dkr.ecr.ap-south-1.amazonaws.com/recommendationservice
appReplicas: 2
containerPort: 8080
containerEnvVars: 
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"

servicePort: 8080
appVersion: "latest"
