appName: shippingservice
appImage: 667516053986.dkr.ecr.ap-south-1.amazonaws.com/shippingservice
appVersion: 1
appReplicas: 2
containerPort: 50051
containerEnvVars: 
- name: PORT
  value: "50051"

servicePort: 50051