appName: emailservice
imageName: docker.io/c0dysharma/ms-emailservice
imageTag: latest
appReplicas: 2
containerPort: 8080
containerEnvVars:
  - name: PORT
    value: "8080"

serviceType: ClusterIP
servicePort: 5000
